[build]
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  NPM_FLAGS = "--include=dev"

# Add headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # PWA headers
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Caching headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caching headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Redirect all traffic to index.html (SPA handling)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s - SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false

# Handle service worker scope
[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  headers = { ServiceWorker = "script" }
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
