[build]
  command = "npm run build"
  publish = "dist"
  environment = { 
    NODE_VERSION = "18", 
    NODE_ENV = "production",
    SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  }

# Add headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Redirect all traffic to HTTPS
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
